### ISSUE TITLE
Installed Plugin Creates Fatal Error

### ISSUE THREAD

**Issue by KyleFreedomSeeds** [jmanpenilla/MiniMOTD#18]
Velocity version 1.0.10 will not run with this installed.
Velocity downloaded from website as latest build (#244, 14 Sep 2020)

See Error Below:

19.09 20:45:08 [Server] INFO Booting up Velocity 1.0.10-SNAPSHOT (git-79d50abe-b244)...
19.09 20:45:08 [Server] INFO Connections will use epoll channels, native (Linux amd64) compression, Java ciphers
19.09 20:45:08 [Server] INFO Loading plugins...
19.09 20:45:09 [Server] ERROR Exception in thread "main" java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
19.09 20:45:09 [Server] ERROR at java.lang.Class.getDeclaredConstructors0(Native Method)
19.09 20:45:09 [Server] ERROR at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
19.09 20:45:09 [Server] ERROR at java.lang.Class.getDeclaredConstructors(Class.java:2020)
19.09 20:45:09 [Server] ERROR at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:243)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:115)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:717)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:54)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:36)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:49)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:99)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:54)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:186)
19.09 20:45:09 [Server] ERROR at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:105)
19.09 20:45:09 [Server] ERROR at com.google.inject.Guice.createInjector(Guice.java:87)
19.09 20:45:09 [Server] ERROR at com.google.inject.Guice.createInjector(Guice.java:69)
19.09 20:45:09 [Server] ERROR at com.google.inject.Guice.createInjector(Guice.java:59)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:77)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:98)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:245)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:205)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.Velocity.main(Velocity.java:47)
19.09 20:45:09 [Server] ERROR Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66)
19.09 20:45:09 [Server] ERROR at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43)
19.09 20:45:09 [Server] ERROR at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
19.09 20:45:09 [Server] ERROR ... 23 more
19.09 20:45:09 [Multicraft] Server shut down (stopping)

**Comment by KyleFreedomSeeds** [comment]
Required to go to Jenkins and download the latest build directly (#249 as of writing). Not compatible with the build from the velocity website. (#244 as of writing)

**Comment by jmanpenilla** [comment]
MiniMOTD for Velocity works only with Velocity 1.1+. 1.0.x builds are not compatible
