### ISSUE TITLE
no gradient

### ISSUE THREAD

**Issue by arceuss** [jmanpenilla/MiniMOTD#25]
![image](https://user-images.githubusercontent.com/28229451/96802823-e8cb7680-13c7-11eb-97e2-7b497bb20e20.png)
![image](https://user-images.githubusercontent.com/28229451/96802836-ecf79400-13c7-11eb-9f89-918093797510.png)
using paper

**Comment by jmanpenilla** [comment]
the config you shared a screenshot of is for the fabric mod not the plugin. also, github issues is not for support.
